# Generated by Django 6.0.8 on 2026-09-10 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.TextField(blank=True, help_text='Original sales call transcript')),
                ('summary', models.TextField(blank=True, help_text='One-sentence brutal summary')),
                ('died', models.CharField(blank=True, help_text='KPI X at Step Y — why', max_length=255)),
                ('scorecard', models.JSONField(blank=True, default=list, help_text='Per-KPI scores [{n, score, note}]')),
                ('failures', models.JSONField(blank=True, default=list, help_text='Failed KPIs with transcript quotes [{kpi, quote, why}]')),
                ('scenario_tags', models.JSONField(blank=True, default=list, help_text='Objection scenarios tagged [{scenario, handled, note}]')),
                ('assigned_drills', models.JSONField(blank=True, default=list, help_text='Drills assigned from grade [{name, sets, pass}]')),
                ('overall_pass', models.BooleanField(default=False, help_text='Whether the call was graded as passing')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call Grade',
                'verbose_name_plural': 'Call Grades',
                'ordering': ['-graded_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeKpiScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kpi_number', models.IntegerField(help_text='KPI number (1-22)')),
                ('score', models.CharField(help_text='pass|partial|fail|na', max_length=10)),
                ('note', models.TextField(blank=True, help_text='Grader note')),
                ('call_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_scores', to='grades.callgrade')),
            ],
            options={
                'verbose_name': 'Grade KPI Score',
                'verbose_name_plural': 'Grade KPI Scores',
                'ordering': ['kpi_number'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(help_text='Name of the quiz/exam', max_length=255)),
                ('quiz_index', models.IntegerField(default=0, help_text='Quiz index (0-2 for rank exams)')),
                ('total_questions', models.IntegerField(default=0, help_text='Total questions in quiz')),
                ('correct_count', models.IntegerField(default=0, help_text='Number of correct answers')),
                ('score_percent', models.IntegerField(default=0, help_text='Score as percentage')),
                ('passed', models.BooleanField(default=False, help_text='Whether the pass threshold (80%) was met')),
                ('missed_topics', models.JSONField(blank=True, default=list, help_text='List of missed question topics [{q, you, ans, w}]')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
