# Generated by Django 6.0.8 on 2026-09-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('pass_updated', 'Password Updated'), ('player_joined', 'Player Joined')], max_length=50),
        ),
    ]
