# Generated by Django 6.0.8 on 2026-09-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('pass_updated', 'Password Updated'), ('pass_changed', 'Password Changed'), ('player_joined', 'Player Joined'), ('rank_upgraded', 'Rank Upgraded'), ('quiz_passed', 'Quiz Passed'), ('quiz_failed', 'Quiz Failed'), ('call_graded', 'Call Graded'), ('assignment_completed', 'Assignment Completed'), ('card_mastered', 'Card Mastered'), ('drill_milestone', 'Drill Milestone'), ('custom_training_completed', 'Custom Training Completed'), ('protocol_phase_advanced', 'Protocol Phase Advanced'), ('protocol_recall_streak', 'Protocol Recall Streak'), ('anchor_mastered', 'Anchor Mastered'), ('protocol_drill_passed', 'Protocol Drill Passed'), ('weekly_session_logged', 'Weekly Session Logged')], max_length=50),
        ),
    ]
