# Generated by Django 6.0.8 on 2026-09-10 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=0, help_text='Current rank (0-3)')),
                ('best', models.JSONField(blank=True, default=dict, help_text='Best quiz scores by rank index {rank: score%}')),
                ('custom_done', models.IntegerField(default=0, help_text='Number of custom training sessions completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The player this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Assignment title', max_length=255)),
                ('why', models.TextField(blank=True, help_text='Why this was assigned')),
                ('sets', models.IntegerField(default=2, help_text='Number of sets to complete')),
                ('pass_condition', models.TextField(blank=True, help_text='Pass condition')),
                ('done', models.BooleanField(default=False, help_text='Mark as complete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_list', to='progression.userprogress')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserKpiStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kpi_number', models.IntegerField(help_text='KPI number (1-22)')),
                ('pass_count', models.IntegerField(default=0)),
                ('partial_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_stats', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_stat_list', to='progression.userprogress')),
            ],
            options={
                'verbose_name': 'KPI Statistic',
                'verbose_name_plural': 'KPI Statistics',
                'ordering': ['kpi_number'],
                'unique_together': {('user', 'kpi_number')},
            },
        ),
        migrations.CreateModel(
            name='UserDrill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drill_number', models.IntegerField(help_text='Drill number (1-N)')),
                ('sets_completed', models.IntegerField(default=0, help_text='Number of sets completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_progress', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drill_list', to='progression.userprogress')),
            ],
            options={
                'verbose_name': 'Drill Progress',
                'verbose_name_plural': 'Drill Progress',
                'ordering': ['drill_number'],
                'unique_together': {('user', 'drill_number')},
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_index', models.IntegerField(help_text='Index of the card in CARDS array')),
                ('mastery', models.IntegerField(default=0, help_text='0=not seen, 1=seen once, 2+=mastered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_list', to='progression.userprogress')),
            ],
            options={
                'verbose_name': 'Card Progress',
                'verbose_name_plural': 'Card Progress',
                'ordering': ['card_index'],
                'unique_together': {('user', 'card_index')},
            },
        ),
        migrations.CreateModel(
            name='UserScenarioStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_number', models.IntegerField(help_text='Scenario number (1-20)')),
                ('count', models.IntegerField(default=0, help_text='Total times encountered')),
                ('fail_count', models.IntegerField(default=0, help_text='Times handled off-methodology')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_stat_list', to='progression.userprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scenario Statistic',
                'verbose_name_plural': 'Scenario Statistics',
                'ordering': ['scenario_number'],
                'unique_together': {('user', 'scenario_number')},
            },
        ),
    ]
