# Generated by Django 6.0.8 on 2026-09-10 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.IntegerField(default=1, help_text='Current training phase (1-4)')),
                ('p1_dates', models.JSONField(blank=True, default=list, help_text='Dates when Phase 1 recall was completed')),
                ('anchor_reps', models.JSONField(blank=True, default=dict, help_text='Anchor script reps by index {index: count}')),
                ('d12_pass', models.JSONField(blank=True, default=dict, help_text='Drill pass conditions {drill_number: bool}')),
                ('weekly_sessions', models.JSONField(blank=True, default=list, help_text='Weekly session history [{drill_number, date}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The player this protocol belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Protocol',
                'verbose_name_plural': 'User Protocols',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnchorRep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor_index', models.IntegerField(help_text='Anchor script index (0-N)')),
                ('rep_number', models.IntegerField(help_text='Rep number (1-5)')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_reps_detail', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchor_rep_details', to='protocol.userprotocol')),
            ],
            options={
                'verbose_name': 'Anchor Rep',
                'verbose_name_plural': 'Anchor Reps',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'anchor_index', 'rep_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drill_number', models.IntegerField(help_text='Drill number (1-N)')),
                ('session_date', models.DateField(help_text='Date of session')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Session duration', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_session_details', to='protocol.userprotocol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_sessions_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Session',
                'verbose_name_plural': 'Weekly Sessions',
                'ordering': ['-session_date'],
                'unique_together': {('user', 'drill_number', 'session_date')},
            },
        ),
    ]
